Knot theory fixes
mathics/Mathics pull request #1199
Opened 2021-03-25 00:42 UTC by mmatera

2021-03-25 01:10 UTC, rocky commented
@mmatera  think I understand how to write the type table-lookup code I was describing in a rough way. 

What would help though is are some useful tests that come up.

2021-03-25 12:18 UTC, rocky commented on mathics/builtin/files.py
> +            if types.get_head_name() == "System`Hold":
This seems hoaky since the speck seems to allow any function and not just `Hold[]` right?

2021-03-25 12:26 UTC, rocky requested changes
Please let's start splitting this up into the individual pieces and create separate PRs for this.

For example Setting System`Notebooks is a thing in of itself and not even needed for Feyncalc.

That could be merged in by itself.

The problem with these growing grab-bag PRs is that they are impossible to review and the quality can suffer because we can't focus on individual features. 

And then they are continually merged (when rebasing instead of merging would lead to more comprehensible results)

2021-03-25 12:26 UTC, rocky commented on mathics/builtin/strings.py
> +    <dt>'StringSplit[{$s_1$, $s_2, $\ldots$}, {"$d1$", "$d2$", ...}]'
Note that ldots doesn't render in the Django interface.

2021-04-01 21:37 UTC, mmatera commented
Spli

> Please let's start splitting this up into the individual pieces and create separate PRs for this.
> 
> For example Setting System`Notebooks is a thing in of itself and not even needed for Feyncalc.
> 
> That could be merged in by itself.
> 
> The problem with these growing grab-bag PRs is that they are impossible to review and the quality can suffer because we can't focus on individual features.
> 
> And then they are continually merged (when rebasing instead of merging would lead to more comprehensible results)

Splitted on #1219, #1209 #1216, #1217

2021-04-03 11:36 UTC, rocky commented
Superceded by other PRs.

2021-04-03 11:36 UTC, closed without merging